services:
  backend:
    build:
      context: .                  # ðŸ‘ˆ usa toda la carpeta del proyecto
      dockerfile: backend/Dockerfile
    network_mode: host
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 9000
    volumes:
      - ./backend/uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: printing-frontend:latest
    ports:
      - "4200:80"
    restart: unless-stopped
